/**
 * @fileoverview gRPC-Web generated client stub for com.practicetest.grpc
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.14.0
// source: greeting.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as greeting_pb from './greeting_pb';


export class GreetingServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorgreeting = new grpcWeb.MethodDescriptor(
    '/com.practicetest.grpc.GreetingService/greeting',
    grpcWeb.MethodType.UNARY,
    greeting_pb.GreetingRequest,
    greeting_pb.GreetingResponse,
    (request: greeting_pb.GreetingRequest) => {
      return request.serializeBinary();
    },
    greeting_pb.GreetingResponse.deserializeBinary
  );

  greeting(
    request: greeting_pb.GreetingRequest,
    metadata: grpcWeb.Metadata | null): Promise<greeting_pb.GreetingResponse>;

  greeting(
    request: greeting_pb.GreetingRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: greeting_pb.GreetingResponse) => void): grpcWeb.ClientReadableStream<greeting_pb.GreetingResponse>;

  greeting(
    request: greeting_pb.GreetingRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: greeting_pb.GreetingResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/com.practicetest.grpc.GreetingService/greeting',
        request,
        metadata || {},
        this.methodDescriptorgreeting,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/com.practicetest.grpc.GreetingService/greeting',
    request,
    metadata || {},
    this.methodDescriptorgreeting);
  }

}

